### PR TITLE
Few proposes to update

### PR DESCRIPTION
**Pull request by milo**
Hi, this addon is great! I would like to propose you some updates.

If it is not acceptable for you, it's ok. Just cherry pick what you want.

### CODE REVIEW

**Comment by romanmatyus** [comment]
Great work! Thank you for collaboration!

I miss your copyright :)

**Comment by milo** [comment]
Actually I didn't add any code, so it's ok.

**Comment by milo** [comment]
Btw. I didn't test all functionality. So, be careful, these are just hot changes.

**Comment by milo** [comment]
I guess, that's all from me for now.

**Pull request merged**
